### PR TITLE
requests auth helper (rewritten)

### PR DESCRIPTION
**Pull request by metheoryt**
Current helper does not work, so I decided to rewrite it for more convenient usage. 
Feel free to move or change the code.
Python 3.6+

### CODE REVIEW

**Comment by metheoryt** [comment]
Anyone please?

**Comment by ech0s7r** [comment]
Hi @metheoryt,

Thank you for your contribution and for creating this PR. 

Could you please open a related [issue](https://github.com/Mastercard/oauth1-signer-python/issues/new/choose) providing [this](https://github.com/Mastercard/oauth1-signer-python/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) information and a description of what is the issue? 
Why the current *helper* doesn't work for you?

Thanks!

**Comment by metheoryt** [comment]
Here it is #19
There is no bug I guess, but we had a headaches with how the signer is written/

**Comment by ech0s7r** [comment]
Closing this PR as it has been merged with: https://github.com/Mastercard/oauth1-signer-python/pull/29.

**Pull request closed without merging**
