### PR TITLE
Fix #21 invalid percent encoding

### LINKED ISSUE #21: [BUG] Invalid base string encoding implementation
#### Bug Report Checklist

- [x] Have you provided a code sample to reproduce the issue?
- [x] Have you tested with the latest release to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

**Description**
We are using this library to authorize our requests to the mastercard Secure Card on File API.

Thank you for this library, guys. It is small and neat, which is perfect to be embeddable in our secure environments.

But we had experienced issues while performing `GET` request with query parameters in it, since some of our query parameters' values contain `reserved` URL characters e.g. `serivceId=Foo#Bar`.
When supplying such a parameter in Mastercard's API and applying, of course, OAuth1 authorization, Mastercards' backend complains our OAuth1 base string is invalid. By comparing base string evaluated by `oauth1-signer-python` with the backends' one, we can see what differences occur in positions with `reserved` characters.

**To Reproduce**
1. Put `print(base_string)` statement inside of `OAuth.get_oauth_parameters` methods right after base string evaluation
1. Form any request with, for example, character `#` in URI. Like `http://..../XXX%23YYY/` or `https://.../?foo=b%23ar`
2. Apply OAuth1 signature performed by `oauth1-signer-python`.
3. Send it to mastercard's backend (or any backend with rfc5849 OAuth1 validator)

**Actual behavior**
oauth1-signer-python base string (a slice)
```
%26serviceId%3DMyService%23Identifier%26
```
mastercard's SCF backend base string (a slice from backend's error message)
```
%26serviceId%3DMyService%2523Identifier%26
```

**Screenshots**

**Additional context**
My platform is Ubuntu 18 with Python 3.8 on the board, but for me it seems like issue is platform independent.

**Related issues/PRs**
Has a similar issue/PR been reported/opened before?

**Suggest a fix/enhancement**
My suggestion is to apply rfc3986 percent encoding algorithm in rfc5849-compliant way:
* unreserved characters MUST NOT be encoded
* other characters MUST be encoded with percent encoding
Also we have to keep out environments' specifics (Python) in mind.

##### Details
After studying https://tools.ietf.org/html/rfc5849 I realized that oauth1-signer-python implementation is not rfc5849-compliant.
These two pieces of code are the source of incompliance
https://github.com/Mastercard/oauth1-signer-python/blob/master/oauth1/coreutils.py#L65
https://github.com/Mastercard/oauth1-signer-python/blob/master/oauth1/coreutils.py#L100

###### First incompliance
https://github.com/Mastercard/oauth1-signer-python/blob/master/oauth1/coreutils.py#L65
Let's discuss this first one, which is related to parameters normalization procedure
Take a closer look at https://tools.ietf.org/html/rfc5849#section-3.4.1.3 describing **request** parameters transmission
Taking about query parameters:
1. First, we have to fully decode those parameters, what is performed here https://github.com/Mastercard/oauth1-signer-python/blob/master/oauth1/coreutils.py#L46
2. Then we have to encode each parameter according to https://tools.ietf.org/html/rfc5849#section-3.6, which says what 
    * `(ALPHA, DIGIT, "-", ".", "_", "~")` MUST NOT be encoded
    * All other characters MUST be encoded

This is where the first incompliance at. This line especially https://github.com/Mastercard/oauth1-signer-python/blob/master/oauth1/coreutils.py#L72 considers `/` to be `safe` while according to rfc5849 it MUST be encoded.
So taking for example `foo=b/r` when rfc5849-compliant parameters normalization procedure produces `foo=b%2Fr`, oauth1-signer procedure produces `foo=b/r`, which is incorrect.

###### Second incompliance
https://github.com/Mastercard/oauth1-signer-python/blob/master/oauth1/coreutils.py#L100
This piece of code is used generally to perform rfc3986 encoding of URI, method, normalized params, oauth parameters.
And this is actualy the reason we faced issues with Mastercards' API.
Somehow this function considers `%` to be **safe** character, whereas it MUST be encoded according to https://tools.ietf.org/html/rfc5849#section-3.6.

###### Other solutions across the Internet
After hacking oauth1-signer in order to force it to produce correct base string (according to my understanding of specs), I want to validate my idea in other people code in the Internet.
I found this library
https://github.com/oauthlib/oauthlib
This is another library which focuses on OAuth1/OAuth2 protocols. Although it's larger so it is harder for us to adopt this one and embed it in our secure environments.
But still, let's look how they perform percent encoding procedure: 
https://github.com/oauthlib/oauthlib/blob/master/oauthlib/oauth1/rfc5849/utils.py#L53

Aha! This one perfectly matches to my idea about rfc5849 encoding

###### Demo playground
This is the comparison between oauth1-signer and oauthlib. oauthlibs' output matches my idea about rfc5849 and provides correct base string in order to authorize in Mastercards' API
https://repl.it/@huumanoid/OAuth1SignerPythonBaseStrings

### PR DESCRIPTION
**Pull request by huumanoid**
### PR checklist

- [x] An issue/feature request has been created for this PR
- [x] Pull Request title clearly describes the work in the pull request and the Pull Request description provides details about how to validate the work. Missing information here may result in a delayed response.
- [x] File the PR against the `master` branch
- [x] The code in this PR is covered by unit tests

#### Description
Playground: https://repl.it/@huumanoid/OAuth1SignerPythonBaseStrings-Fixed#main.py
This PR fixes percent encoding issues described in related issue in details.
This fix also adopts oauthlib's experience in effort to support various python3 versions

### CODE REVIEW

**Comment by rossphelan** [comment]
Hi @huumanoid 

Thanks for submitting a PR!

I checked out and ran your code against a test service and I noticed this introduced some new errors with special characters. Query params containing !, * or $ will cause authentication to fail. % causes it to fail too but that is an existing issue.

**Review by rossphelan — CHANGES_REQUESTED** [review]
Hi @huumanoid

Thanks for submitting a PR!

I checked out and ran your code against a test service and I noticed this introduced some new errors with special characters. Query params containing !, * or $ will cause authentication to fail. % causes it to fail too but that is an existing issue.

Here are the cases I ran against it the test service and the response

Query Param | Master | Fix
-- | -- | --
ABCDEF | OK | OK
ABCDEF1234 | OK | OK
A%BCDEF1234 | AUTHENTICATION_FAILED | AUTHENTICATION_FAILED
A!BCDEF1234 | OK | AUTHENTICATION_FAILED
A*BCDEF1234 | OK | AUTHENTICATION_FAILED
A.BCDEF1234 | OK | OK
A~BCDEF1234 | OK | OK
A-BCDEF1234 | OK | OK
A+BCDEF1234 | AUTHENTICATION_FAILED | OK
A$BCDEF1234 | OK | AUTHENTICATION_FAILED

**Comment by huumanoid** [comment]
Hi @rossphelan and thank you for your review!
Thank you for being so attentive to my PR.

However, I can not reproduce the issue you noted. At least in the manner I test it.
I test this issue against the sandbox api endpoints.
1. As I mentioned in the related issue, my `serviceId` contains such an unsafe character. So I replace my `serviceId` with a test payload `ABCDEF1234` when performing API request, which renders my request to be unauthorized, **yet authenticated** by OAuth 1.0 (baked by both `oauth1-signer-python#master` and `oauth1-signer-python#ISSUE-21_fix-encoding` of course, because there is no more unsafe character supplied).
2. Then I try to play with special characters like `"serviceId=ABCDEF!@#$%^&*()~,./ =+;:><{}^`_1234"`, then send it to API.
3. Whenether I send request baked by `oauth1-signer-python#master`, I get OAuth authentication error. While using `oauth1-signer-python#ISSUE-21_fix-encoding` I receive forbidden error (which means my OAuth 1.0 signature assumed to be valid by API).

What is more interesting, even `"serviceId=A$BCDEF1234"`, ``"serviceId=A*BCDEF1234"`` and `"serviceId=A%BCDEF1234"` lead to OAuth1 error when request was performed with `oauth1-signer-python#master`, but I don't face such an issue after applying my fix.

I tried several endpoints, with both GET and POST among them, and still can't trigger the behavior you described.

How could we figure out what is going on?

**Comment by rossphelan** [comment]
Hi @huumanoid ,

I've just sent you an email, so I can send on the script I've been using to test

**Comment by rossphelan** [comment]
Hi @huumanoid , any progress on this? Did you get a chance to look at the script I sent?

**Comment by rfeelin** [comment]
Closed due to inactivity

**Pull request closed without merging**
